// Trust Centre documents — Privacy, Responsible AI, Accessibility.
// Plain-language commitments grounded in how the platform actually works;
// no certifications or guarantees are claimed that we do not hold.

export type PolicySection = {
  heading: string;
  body?: string[];
  bullets?: string[];
};

export type PolicyDoc = {
  slug: string;
  title: string;
  description: string;
  updated: string;
  lead: string;
  sections: PolicySection[];
};

export const trustCentre: PolicyDoc[] = [
  {
    slug: "privacy",
    title: "Privacy",
    description: "How Cheers Wisdom collects, uses and protects personal data across its platform and programs.",
    updated: "22 July 2026",
    lead: "Cheers Wisdom builds AI that observes and guides human wellbeing. That work is impossible without trust, so privacy is a design constraint — not a checkbox. This page explains, in plain language, what we collect, why, and the choices you have.",
    sections: [
      {
        heading: "What this covers",
        body: [
          "This statement covers the Cheers Wisdom website and the Cheers platform applications — including patient, student, workforce and driver programs — operated by Cheers Wisdom and its deployment partners.",
          "Clinical and school programs always run together with the partner institution (a hospital, school or agency). In those programs, the partner remains the primary guardian of its patients', students' or employees' data, and program-specific consent documents take precedence over this general statement.",
        ],
      },
      {
        heading: "What we collect",
        bullets: [
          "Information you provide directly: account details, daily check-ins, journal entries, mood and symptom reports.",
          "Signals generated by using the platform: engagement patterns, responses to prompts, and device-level usage relevant to the program you are enrolled in.",
          "Program information from partner institutions, such as enrolment details for a recovery or school wellbeing program.",
          "Website basics: the pages you visit on this site. We do not run invasive cross-site tracking on cheerswisdom.com.",
        ],
      },
      {
        heading: "Consent comes first",
        body: [
          "People are enrolled into programs with informed consent — patients at enrolment, students through their school with parent or guardian consent, employees through their organisation's program. You can withdraw from a program at any time through the program's contact point or by writing to us.",
          "Where individual stories or outcomes are shared publicly — for example a patient experience on this site — they are published only with explicit consent.",
        ],
      },
      {
        heading: "How data is used",
        bullets: [
          "To provide the service itself: personalised check-ins, guidance and timely alerts for the person using the platform.",
          "To give the responsible professionals — clinicians, counsellors, safety managers — the visibility the program was set up to provide.",
          "To measure program outcomes against agreed baselines, reported to the partner institution.",
          "For research and publication only in de-identified or aggregated form, under the oversight of the study's investigators and ethics processes.",
        ],
      },
      {
        heading: "What we do not do",
        bullets: [
          "We do not sell personal data.",
          "We do not use program data for advertising.",
          "We do not share identifiable data outside the program it was collected for, except where the law requires it.",
        ],
      },
      {
        heading: "Security",
        body: [
          "Data is protected with encryption in transit, role-based access through separate patient, clinician and administrator portals, and access limited to the people who need it for the program. No system is perfectly secure, and we treat security as continuous work rather than a finished state.",
        ],
      },
      {
        heading: "Your choices",
        body: [
          "You can request access to, correction of, or deletion of your personal data, and you can withdraw from a program at any time. Write to support@cheerswisdom.com and we will route your request to the right team. Where a partner institution controls the program data, we will connect you with them and support the request.",
        ],
      },
    ],
  },
  {
    slug: "responsible-ai",
    title: "Responsible AI",
    description: "The principles and oversight behind Cheers Wisdom's human-first, science-led AI.",
    updated: "22 July 2026",
    lead: "Our platform observes human state and intervenes in human lives — recovery after surgery, a student's digital wellbeing, a driver's alertness. That demands a higher bar than ordinary software. These are the principles we hold ourselves to, and the oversight that keeps us honest.",
    sections: [
      {
        heading: "Evidence before claims",
        body: [
          "Every domain follows the same discipline: name the human challenge, apply the platform, measure the outcome, publish the evidence. Where outcomes are not yet measured, we say so — on this site, metrics that are not yet real are marked as such, never invented. Our first peer-reviewed clinical work is published in JACC, and studies in other domains are in progress with named investigators.",
        ],
      },
      {
        heading: "Humans stay in the loop",
        body: [
          "The AI raises awareness; people make decisions. Clinical alerts route to care teams, school signals route to counsellors and parents, safety signals route to safety managers. The platform is designed to make the responsible human earlier and better informed — not to replace them.",
        ],
      },
      {
        heading: "Transparency with the people observed",
        body: [
          "People know what the platform observes and why. Digital behaviour is understood through consented, transparent methods, and every program states its purpose plainly to the people in it — patients, students and families, workers.",
        ],
      },
      {
        heading: "Proportionality",
        body: [
          "We collect what the program needs and no more. A recovery program observes recovery signals; a cyber-wellbeing program observes digital-behaviour patterns. Observation is scoped to the outcome the program exists to improve.",
        ],
      },
      {
        heading: "Safety boundaries",
        body: [
          "The platform is a wellbeing and awareness companion. It is not an emergency service and does not replace professional diagnosis or treatment. Where the platform detects concerning signals, its job is to bring the right humans in quickly.",
        ],
      },
      {
        heading: "Oversight",
        body: [
          "The scientific direction of the platform is overseen by an independent Scientific Advisory Board, and clinical work runs under named principal investigators at partner institutions, with ethics review as part of every research protocol. Their names are public on this site — accountability starts with being identifiable.",
        ],
      },
      {
        heading: "Raising concerns",
        body: [
          "If you believe the platform has behaved in a way that conflicts with these principles, tell us at support@cheerswisdom.com. Reports go to the team responsible for the program, and to the advisory oversight where warranted.",
        ],
      },
    ],
  },
  {
    slug: "accessibility",
    title: "Accessibility",
    description: "Cheers Wisdom's accessibility commitments for this website and the Cheers platform.",
    updated: "22 July 2026",
    lead: "Wellbeing technology is used by people recovering from surgery, students, older adults and people under stress. If it is not accessible, it does not work — for exactly the people it exists for. This page describes what we do today and where we are still improving.",
    sections: [
      {
        heading: "Our standard",
        body: [
          "We design this website and the Cheers applications toward WCAG 2.2 level AA. We do not claim full conformance today; we treat the guidelines as the working bar for every new feature and redesign.",
        ],
      },
      {
        heading: "What is built in today",
        bullets: [
          "Reduced motion: animations across the site and platform respect the system 'reduce motion' preference.",
          "Keyboard operability: interactive elements — including galleries, viewers and selectors — are usable with a keyboard, with visible focus states.",
          "Semantic structure: headings, landmarks and labels for assistive technologies, and alt text on meaningful images.",
          "Readable type and contrast on both light and dark surfaces.",
        ],
      },
      {
        heading: "In the platform",
        bullets: [
          "Daily check-ins are designed to be short, simple and forgiving — built for people in recovery, not power users.",
          "Voice-based interaction is available in the health companion for people who prefer speaking to typing.",
          "Programs run in the person's preferred language where the deployment supports it.",
        ],
      },
      {
        heading: "Known limitations",
        body: [
          "Some older photographs and third-party embeds may lack complete descriptions, and some complex visualisations are still being improved for screen-reader users. We prioritise fixes that affect core journeys first — check-ins, alerts and reports.",
        ],
      },
      {
        heading: "Tell us what's broken",
        body: [
          "If something on this site or in a Cheers application is hard or impossible for you to use, we want to know. Write to support@cheerswisdom.com with the page or screen and what happened — accessibility reports are treated as defects, not feedback.",
        ],
      },
    ],
  },
];
